data_args:
  body_type: smplx
  cfg_path: ./config_files/config_hydra/motion_primitive/finedance_h2_f8_r8.yaml
  data_dir: ./data/finedance
  dataset: finedance
  enforce_gender: male
  enforce_zero_beta: 1
  feature_dim: 276
  future_length: 8
  history_length: 2
  num_primitive: 8
  prob_static: 0.0
  text_tolerance: 0.0
  weight_scheme: uniform_samp:0.
denoiser_args:
  diffusion_args:
    diffusion_steps: 1000
    noise_schedule: cosine
    respacing: ''
    sigma_small: true
  model_args:
    activation: gelu
    cond_mask_prob: 0.1
    dropout: 0.1
    h_dim: 512
    history_shape: !!python/tuple
    - 2
    - 276
    music_dim: 35
    n_blocks: 2
    noise_shape: !!python/tuple
    - 1
    - 256
  model_type: mlp
  mvae_path: ./mvae/mvae_finedance_h2_f8_r8/checkpoint_200000.pt
  rescale_latent: 1
  train_rollout_history: rollout
  train_rollout_type: full
device: cuda
exp_name: mld_finedance_h2_f8_r8
save_dir: !!python/object/apply:pathlib.PosixPath
- mld_denoiser
- mld_finedance_h2_f8_r8
seed: 0
torch_deterministic: true
track: 1
train_args:
  anneal_lr: 1
  batch_size: 128
  ema_decay: 0.999
  grad_clip: 1.0
  learning_rate: 0.0001
  log_interval: 1000
  resume_checkpoint: null
  save_interval: 100000
  stage1_steps: 100000
  stage2_steps: 100000
  stage3_steps: 100000
  use_amp: 0
  use_predicted_joints: 0
  val_interval: 10000
  weight_feature_rec: 0.0
  weight_joints_consistency: 0.0
  weight_joints_delta: 0.0
  weight_kl: 0.0001
  weight_latent_rec: 1.0
  weight_orient_delta: 0.0
  weight_rec: 1.0
  weight_smpl_joints_rec: 0.0
  weight_transl_delta: 0.0
wandb_entity: interaction
wandb_project_name: mld_denoiser
